DibaEShop/DibaEShop.Web/Areas/Admin/Controllers/ProductController.cs
using DibaEShop.Models;
using DibaEShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.Extensions.Hosting;

namespace DibaEShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class ProductController : Controller
    {
        private readonly DataAccess.Repository.IRepository.IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _HostEnvironment; // برای بدست آوردن آخرین آدرس تا wwwroot
        public ProductController(DataAccess.Repository.IRepository.IUnitOfWork unitOfWork, IWebHostEnvironment HostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _HostEnvironment = HostEnvironment;
        }

        public IActionResult Index()
        {

            IEnumerable<Product> products = _unitOfWork.Product.GetAll();
            return View(products);

        }

        //onget
        public IActionResult Upsert(int? productId)
        {
            var productVM = new ProductVM()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.CategoryId.ToString()
                }).ToList()
            };

            if (productId == null || productId == 0)
            {
                //create product
                return View(productVM);
            }
            else
            {  //update product
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.ProductId == productId);
                return View(productVM);


            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _HostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\product");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"\images\product\" + fileName + extension;

                }
                if (obj.Product.ProductId == 0)
                {
                  
                    _unitOfWork.Product.Add(obj.Product);

                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                }
               
                _unitOfWork.Save();
                //TempData["success"] ="Product created successfully";
                //return Redirect("/Admin/product/Index");
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        #region API CALLS
        [HttpGet]
        [Route("/Admin/Product/GetAll")]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties: "Category");
            return Json(new { data = productList });
        }


        [HttpDelete]
        public IActionResult Delete(int? productId)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.ProductId == productId);
            if (obj == null)
            {
                //TempData["error"] = "Product Create not done";
                return Json(new { success = false, message = "Error while deleting" });

            }

            var oldImagePath = Path.Combine(_HostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Product.Remove(obj);
          //  _unitOfWork.Product.SoftDelete(obj);
            _unitOfWork.Save();
           
            return Json(new { success = true, message = "Delete Successful" });

        }

        #endregion



    }
}

DibaEShop/DibaEShop.Web/Areas/Admin/Controllers/UserController.cs
using DibaEShop.DataAccess.Repository.IRepository;
using DibaEShop.Models;
using DibaEShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using System.Runtime.InteropServices;

namespace DibaEShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<ApplicationUser> users = _unitOfWork.ApplicationUser.GetAll();
            return View(users);
        }

        //Get
        public IActionResult Update(string id)
        {
            var user = _unitOfWork.ApplicationUser.GetUserForEdit(id);
            return View(user);
        }

        ////POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ApplicationUser obj)
        {

            if (!ModelState.IsValid)
                return View(obj);

            var userFromDb = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == obj.Id);

            userFromDb.PhoneNumber = obj.PhoneNumber;
            userFromDb.Address = obj.Address;
            userFromDb.City = obj.City;
            userFromDb.State = obj.State;
            userFromDb.Name = obj.Name;
            userFromDb.PostalCode = obj.PostalCode;
            _unitOfWork.ApplicationUser.Update(userFromDb.Id);
            _unitOfWork.Save();

            return RedirectToAction("Index");



        }


        #region API CALLS
        [HttpGet]
        [Route("/Admin/User/GetAllUser")]
        public IActionResult GetAllUser()
        {
            var UserList = _unitOfWork.ApplicationUser.GetAll();
            return Json(new { data = UserList });
        }


        [HttpDelete]
        public IActionResult Delete(string? Id)
        {
            var obj = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == Id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.ApplicationUser.Remove(obj);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });

        }

        #endregion

    }
}

DibaEShop/DibaEShop.Web/Areas/Customer/Controllers/CartController.cs
using DibaEShop.DataAccess.Repository.IRepository;
using DibaEShop.Models;
using DibaEShop.Models.ViewModels;
using DibaEShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using ZarinpalSandbox;

namespace DibaEShop.Web.Areas.Customer.Controllers
{


    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {


            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new ShoppingCartVM()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product"),
                OrderHeader = new()

            };



            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {
                cart.TotalPrice = (cart.Count) * (cart.Product.Price);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.TotalPrice;
            }
            return View(ShoppingCartVM);
        }


        public IActionResult Plus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);
            cart.Count += 1;
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Minus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);
            if (cart.Count >= 1)
            {
                cart.Count -= 1;
            }
            else
            {
                _unitOfWork.ShoppingCart.Remove(cart);
            }

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }


        public IActionResult Remove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        //httpget
        public IActionResult Summary()
        {
            var claim = (ClaimsIdentity)User.Identity;
            var userId = claim.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == userId
                , includeProperties: "Product"),
                OrderHeader = new()
            };

            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == userId);
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.Address = ShoppingCartVM.OrderHeader.ApplicationUser.Address;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;

            foreach (var cart in ShoppingCartVM.ShoppingCartList)
            {

                cart.TotalPrice = (cart.Count) * (cart.Product.Price);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.TotalPrice;
            }

            return View(ShoppingCartVM);
        }


        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST() // ya bayad vorudi method nue model ru begiram ya bayad az [bindproperty] ruye property hamnue model safhe estfade konam
        {
            var claim = (ClaimsIdentity)User.Identity;
            var userId = claim.FindFirst(ClaimTypes.NameIdentifier).Value;

            //ShoppingCartVM همان propperty  خط19  shopingCartVM [bindproperty] شده
            ShoppingCartVM.ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product");

            ShoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicatioUserId = userId;

            foreach (var item in ShoppingCartVM.ShoppingCartList)
            {
                item.TotalPrice = (item.Count) * (item.Product.Price);
                ShoppingCartVM.OrderHeader.OrderTotal += item.TotalPrice;   
            }

            ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
            ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;

            _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Save();

            foreach (var item in ShoppingCartVM.ShoppingCartList) //به ازای هر آیتم داخل سبد خرید یک <-  orderdetail درج میکنیم
            {
                OrderDetail orderDetail = new()
                {
                    Count = item.Count,
                    OrderId = ShoppingCartVM.OrderHeader.Id, // => order header id
                    Price = item.TotalPrice,
                    ProducId = item.ProductId,

                };
                _unitOfWork.OrderDetail.Add(orderDetail);
                _unitOfWork.Save();
            }


            #region  zarinpal test Online Payment
            var useremail = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == userId).Email;
            var userPhoneNumber = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == userId).PhoneNumber;

            var payment = new Payment((int)ShoppingCartVM.OrderHeader.OrderTotal);
            var res = payment.PaymentRequest("online payment", "https://localhost:7008/OnlinePayment/" + userId, useremail, userPhoneNumber);


            if (res.Result.Status == 100)
            {
                return Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + res.Result.Authority);

            }
       

            return View();
            #endregion


            #region stripe online payment

            //var domain = "https://localhost:44318/";
            //var options = new SessionCreateOptions
            //{
            //    PaymentMethodTypes = new List<string>
            //    {
            //      "card",
            //    },
            //    LineItems = new List<SessionLineItemOptions>(),
            //    Mode = "payment",
            //    SuccessUrl = domain + $"customer/cart/OrderConfirmation?id={ShoppingCartVM.OrderHeader.Id}",
            //    CancelUrl = domain + $"customer/cart/index",
            //};

            //foreach (var item in ShoppingCartVM.ShoppingCartList)
            //{

            //    var sessionLineItem = new SessionLineItemOptions
            //    {
            //        PriceData = new SessionLineItemPriceDataOptions
            //        {
            //            UnitAmount = (long)(item.TotalPrice * 100),//20.00 -> 2000
            //            Currency = "usd",
            //            ProductData = new SessionLineItemPriceDataProductDataOptions
            //            {
            //                Name = item.Product.Title
            //            },

            //        },
            //        Quantity = item.Count,
            //    };
            //    options.LineItems.Add(sessionLineItem);

            //}

            //var service = new SessionService();
            //Session session = service.Create(options);
            //_unitOfWork.OrderHeader.UpdateStripePaymentID(ShoppingCartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            //_unitOfWork.Save();
            //Response.Headers.Add("Location", session.Url);
            //return new StatusCodeResult(303);


            //public IActionResult OrderConfirmation(int id) // stripe pay confirmation
            // {
            //     var orderheader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == id);
            //     var service = new SessionService();
            //     Session session = service.Get(orderheader.SessionId);
            //     if (session.PaymentStatus.ToLower() == "paid")
            //     {
            //         _unitOfWork.OrderHeader.UpdateStatus(id, SD.StatusApproved, SD.PeymentStatusApproved);
            //         _unitOfWork.Save();
            //     }
            //     var shopingList = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == orderheader.ApplicatioUserId).ToList();
            //     _unitOfWork.ShoppingCart.RemoveRange(shopingList);
            //     _unitOfWork.Save();
            //     return View(id);
            // }

            #endregion
        }




    }
}

DibaEShop/DibaEShop.Web/Views/Shared/_Footer.cshtml
<footer class="  text-muted">
    <div class="container   fixed-bottom">
        &copy; 1402 - DibaEShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

DibaEShop/DibaEShop.Web/Views/Shared/_Layout.cshtml
@using DibaEShop.Utility;
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <title>@ViewData["Title"] - DibaEShop</title>
    <partial name="_MetaTags" />
    <partial name="_Styles" />

</head>
<body>
    <partial name="_navBar" />
    <div class="m-3"> @RenderBody()</div>
    <partial name="_Footer" />
    <partial name="_Scripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DibaEShop/DibaEShop.Web/Views/Shared/_MetaTags.cshtml
<meta name="googlebot" content="index,follow">
<meta name="robots" content="noodp,noydir">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

DibaEShop/DibaEShop.Web/Views/Shared/_NavBar.cshtml
@using DibaEShop.Utility;
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <partial name="_LoginPartial" />

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="row collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house"></i>  Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                        <i class="bi bi-sort-up"></i> Manage Order
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                        <i class="bi bi-cart-check"></i> Shopping Cart
                    </a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Call"><i class="bi bi-telephone"></i> call</a>
                </li>
                @if (User.IsInRole(SD.Role_Admin))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="bi bi-person"></i> Admin</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index"><i class="bi bi-people-fill"></i> Users</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index"><i class="bi bi-tags-fill"></i> categories</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index"><i class="bi bi-phone"></i> products</a>
                            <a class="dropdown-item" id="register" asp-area="Identity" asp-page="/Account/Register"><i class="bi bi-person-plus-fill"></i> Register</a>
                        </div>
                    </li>
                }
            </ul>
            <div class="col end-100  ">
                <form asp-area="Customer" asp-controller="Home" asp-action="SearchProduct" method="get">
                    <input class="d-inline-block form-control me-sm-2" id="search" name="search" placeholder="Enter phone name" style="width:275px;" />
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit" style="font-weight:bold;">filter</button>
                </form>
            </div>


        </div>
    </div>
</nav>

DibaEShop/DibaEShop.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

DibaEShop/DibaEShop.Web/Views/Shared/_ProductBox.cshtml
@model DibaEShop.Models.Product

  <div class=" col-md-4 term-col ">


    <div class="  box-border m-2 " >
        <div class="card p-2  card-size">
            <img src="@Model.ImageUrl" class="image-size" />
            <div class="card-body text-center overflow-hidden">
                <p>@Model.Title</p>
                <div class="text-center">
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">"$" price:@Model.Price </p>

                </div>
            </div>
            <div>
                <a class="btn   btn-primary form-control" asp-area="Customer" asp-controller="Home"
                   asp-action="Details" asp-route-productId="@Model.ProductId">Details</a>
            </div>

        </div>
    </div>
</div>

DibaEShop/DibaEShop.Web/Views/Shared/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/SweetAlert.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/js/datatable.js"></script>
<script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

DibaEShop/DibaEShop.Web/Views/Shared/_Styles.cshtml
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/bootstrap.min(4).css" />
<link rel="stylesheet" type="text/css" href="https://common.olemiss.edu/_js/sweet-alert/sweet-alert.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="~/css/datatable.css">
<link rel="stylesheet" href="~/css/productBox.css">